pdd_ecommerce_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: './pdd_analytics.duckdb'
      threads: 4
      extensions:
        - parquet
      settings:
        memory_limit: 4GB
        threads: 4
