pdd_ecommerce_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '{{ env_var("DBT_DUCKDB_PATH", "data/processed/analytics.duckdb") }}'
      threads: 4
      extensions:
        - parquet
      settings:
        memory_limit: 4GB
        threads: 4
